upstream backend_cinema {
    server web:8000;
}

server {
    listen 80;

    server_name potuzhno.cinema.cbu.net;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

; server {
;     listen 443 ssl;
;     server_name potuzhno.cinema.cbu.net;
;
;     ssl_certificate /etc/letsencrypt/live/potuzhno.cinema.cbu.net/fullchain.pem;
;     ssl_certificate_key /etc/letsencrypt/live/potuzhno.cinema.cbu.net/privkey.pem;
;
;     location / {
;         proxy_pass http://web:8000;
;         auth_basic off;
;         proxy_set_header Host $host;
;         proxy_set_header X-Real-IP $remote_addr;
;         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
;         proxy_set_header X-Forwarded-Proto $scheme;
;     }
;
;     location /docs/ {
;         include /etc/nginx/conf.d/auth.conf;
;
;         proxy_pass http://web:8000/docs;
;         proxy_set_header Host $host;
;         proxy_set_header X-Real-IP $remote_addr;
;         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
;         proxy_set_header X-Forwarded-Proto $scheme;
;     }
;
;     location /redoc/ {
;         include /etc/nginx/conf.d/auth.conf;
;
;         proxy_pass http://web:8000/redoc;
;         proxy_set_header Host $host;
;         proxy_set_header X-Real-IP $remote_addr;
;         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
;         proxy_set_header X-Forwarded-Proto $scheme;
;     }
;
;     location /openapi.json {
;         include /etc/nginx/conf.d/auth.conf;
;
;         proxy_pass http://web:8000/openapi.json;
;         proxy_set_header Host $host;
;         proxy_set_header X-Real-IP $remote_addr;
;         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
;         proxy_set_header X-Forwarded-Proto $scheme;
;     }
;
;     location /mailhog/ {
;         include /etc/nginx/conf.d/auth.conf;
;
;         proxy_pass http://mailhog:8025/;
;         proxy_set_header Host $host;
;         proxy_set_header X-Real-IP $remote_addr;
;         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
;         proxy_set_header X-Forwarded-Proto $scheme;
;     }
; }
