services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        APP_ENV: prod
    container_name: online_cinema_api
    env_file:
      - .env
    command: >
      gunicorn src.main:app
      -k uvicorn.workers.UvicornWorker
      --bind 0.0.0.0:8000
      --workers 1
      --timeout 60
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - online_cinema_network
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: cinema_db
    env_file:
      - .env
    volumes:
      - cinema_db_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - online_cinema_network
    restart: unless-stopped

  migrator:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        APP_ENV: prod
    container_name: cinema_migrator
    command: alembic upgrade head
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - online_cinema_network

  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        APP_ENV: prod
    command: celery -A src.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - online_cinema_network
    restart: unless-stopped

  celery-beat:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        APP_ENV: prod
    command: celery -A src.celery_app beat --loglevel=info
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - online_cinema_network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio-cinema
    command: server --console-address ":9001" /data
    env_file:
      - .env
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - online_cinema_network

  minio_setup:
    build:
      context: .
      dockerfile: docker/minio/Dockerfile
    container_name: minio_setup
    depends_on:
      minio:
        condition: service_healthy
    env_file:
      - .env
    environment:
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      BUCKET_NAME: ${S3_BUCKET_NAME}
    networks:
      - online_cinema_network

  redis:
    image: redis:7-alpine
    container_name: cinema_redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
        - online_cinema_network

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe_cli
    command: listen --forward-to web:8000/api/v1/payments/webhooks/stripe --api-key ${STRIPE_SECRET_KEY}
    env_file:
      - .env
    depends_on:
      - web
    restart: on-failure

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    depends_on:
      - web
    env_file:
      - ./configs/nginx/.env
    networks:
      - online_cinema_network
    restart: unless-stopped

volumes:
  cinema_db_data:
  minio_data:

networks:
  online_cinema_network:
    driver: bridge

