CREATE TABLE "user_groups" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "hashed_password" varchar(255) NOT NULL,
  "is_active" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "group_id" int NOT NULL
);

CREATE TABLE "user_profiles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" int UNIQUE NOT NULL,
  "first_name" varchar(100),
  "last_name" varchar(100),
  "avatar" varchar(255),
  "gender" varchar(10),
  "date_of_birth" date,
  "info" text
);

CREATE TABLE "activation_tokens" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" int NOT NULL,
  "token" varchar(255) UNIQUE NOT NULL,
  "expires_at" timestamp NOT NULL
);

CREATE TABLE "password_reset_tokens" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" int NOT NULL,
  "token" varchar(255) UNIQUE NOT NULL,
  "expires_at" timestamp NOT NULL
);

CREATE TABLE "refresh_tokens" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" int NOT NULL,
  "token" varchar(255) UNIQUE NOT NULL,
  "expires_at" timestamp NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("group_id") REFERENCES "user_groups" ("id");

ALTER TABLE "user_profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "activation_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "password_reset_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "refresh_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
