CREATE TABLE "users" (
  "id" int PRIMARY KEY NOT NULL
);

CREATE TABLE "movies" (
  "id" int PRIMARY KEY NOT NULL
);

CREATE TABLE "carts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" int UNIQUE NOT NULL
);

CREATE TABLE "cart_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "cart_id" int NOT NULL,
  "movie_id" int NOT NULL,
  "added_at" timestamp NOT NULL DEFAULT (now())
);

ALTER TABLE "carts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cart_id") REFERENCES "carts" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("id");
