CREATE TABLE "genres" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "stars" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "directors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "certifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "movies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "uuid" uuid UNIQUE NOT NULL,
  "name" varchar(250) NOT NULL,
  "year" int NOT NULL,
  "time" int NOT NULL,
  "imdb" float NOT NULL,
  "votes" int NOT NULL,
  "meta_score" float,
  "gross" float,
  "description" text NOT NULL,
  "price" decimal(10,2),
  "certification_id" int NOT NULL
);

CREATE TABLE "movie_genres" (
  "movie_id" int NOT NULL,
  "genre_id" int NOT NULL,
  PRIMARY KEY ("movie_id", "genre_id")
);

CREATE TABLE "movie_directors" (
  "movie_id" int NOT NULL,
  "director_id" int NOT NULL,
  PRIMARY KEY ("movie_id", "director_id")
);

CREATE TABLE "movie_stars" (
  "movie_id" int NOT NULL,
  "star_id" int NOT NULL,
  PRIMARY KEY ("movie_id", "star_id")
);

ALTER TABLE "movies" ADD FOREIGN KEY ("certification_id") REFERENCES "certifications" ("id");

ALTER TABLE "movie_genres" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("id");

ALTER TABLE "movie_genres" ADD FOREIGN KEY ("genre_id") REFERENCES "genres" ("id");

ALTER TABLE "movie_directors" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("id");

ALTER TABLE "movie_directors" ADD FOREIGN KEY ("director_id") REFERENCES "directors" ("id");

ALTER TABLE "movie_stars" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("id");

ALTER TABLE "movie_stars" ADD FOREIGN KEY ("star_id") REFERENCES "stars" ("id");
