CREATE TABLE "users" (
  "id" int PRIMARY KEY NOT NULL
);

CREATE TABLE "movies" (
  "id" int PRIMARY KEY NOT NULL
);

CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "status" varchar(50) NOT NULL DEFAULT 'pending',
  "total_amount" decimal(10,2)
);

CREATE TABLE "order_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "order_id" int NOT NULL,
  "movie_id" int NOT NULL,
  "price_at_order" decimal(10,2) NOT NULL
);

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("id");
