CREATE TABLE "users" (
  "id" int PRIMARY KEY NOT NULL
);

CREATE TABLE "orders" (
  "id" int PRIMARY KEY NOT NULL
);

CREATE TABLE "order_items" (
  "id" int PRIMARY KEY NOT NULL
);

CREATE TABLE "payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" int NOT NULL,
  "order_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "status" varchar(50) NOT NULL DEFAULT 'successful',
  "amount" decimal(10,2) NOT NULL,
  "external_payment_id" varchar(255)
);

CREATE TABLE "payment_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "payment_id" int NOT NULL,
  "order_item_id" int NOT NULL,
  "price_at_payment" decimal(10,2) NOT NULL
);

ALTER TABLE "payments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "payment_items" ADD FOREIGN KEY ("payment_id") REFERENCES "payments" ("id");

ALTER TABLE "payment_items" ADD FOREIGN KEY ("order_item_id") REFERENCES "order_items" ("id");
